# HOMEWORK 4

In [ ]:
# name     : Arshya Esfandiari
# uni ID   : 40334201
# homework : 4
# problem  : write all of my examples ( optional : all lessons before examples )
#            from session 1405/02/14.
# ------------------------------------------------------------------------------

### Example 1

In [10]:
# یک آرایه ی یک بعدی شامل عدد های 1 تا 10 را ایجاد و 

# 1. تمامی عنصر ها را بر 2 تقسیم کنید
# 2. جذر تمامی عنصر ها را محاسبه کنید
# 3. مجموع ، میانگین و انحراف معیار عدد ها را به دست بیاورید

import numpy as np
# Creating Array
Arr = np.array(range(1,11))
print(f"{Arr}\n")

# Dividing Array Elements
DivArr = Arr/2
print(f"{DivArr}\n")

# Rooting Array Elements
SqrtArr = np.sqrt(Arr)
print(f"{SqrtArr}\n")

# Calculating Sum of Array Elements
SumArr = np.sum(Arr)
print(f"{SumArr}\n")

# Calculating Mean of Array Elements
MeanArr = np.mean(Arr)
print(f"{MeanArr}\n")

# Calculating Standard Deviation of Array Elements
StdArr = np.std(Arr)
print(f"{StdArr}\n")

[ 1  2  3  4  5  6  7  8  9 10]

[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]

55

5.5

2.8722813232690143



### Example 2

In [11]:
# یک ماتریس 3 در 3 از عدد ها یتصادفی صحیح میان 0 تا 100 ایجاد و

# 1. سطر دوم ماتریس را بنویسید
# 2. ستون نخست ماتریس را بنویسید
# 3. مقدار عنصر واقع در سطر نخست ، ستون دوم را تغییر و برابر با 999 قرار دهید
# 4. ماتریس را به یک آرایه ی یک بعدی تبدیل کنید
import numpy as np

Matrix = np.random.randint(0,101,size=(3,3))

Nd2Row = Matrix[1, :]
print(f"{Nd2Row}\n")

St1Col = Matrix[:, 0]
print(f"{St1Col}\n")

Matrix[0,1] = 999
print(f"{Matrix}\n")

# Turn into 1d Array
Flat = Matrix.flatten()
print(f"Flat")

[60 24 67]

[34 60  6]

[[ 34 999  75]
 [ 60  24  67]
 [  6  66  58]]

Flat


### Example 3

In [12]:
# آرایه ای از 20 عدد تصادفی با توزیع نرمال ( میانگین صفر وانحراف معیار 1 ) ایجاد کنید

# 1. یک آرایه ی بولین بسازید که نشان دهد هر عنصر بزرگتر ز 0 است
# 2. تمام عدد های مثبت را در یک آرایه جدید ذخیره کنید
# 3. تعداد عدد های منفی را بشمارید
# 4. تمامی عدد های کوچکتر از -0.5 را با مقدار 0 جایگزین کنید

import numpy as np
# Creating a random array with ~N(0,1)
Arr = np.random.randn(20)
print(f"{Arr}\n")

# A Bool that says which index is greater than 0
IsPositive = Arr > 0

# Save positive numbers in an array
Positives1 = Arr[IsPositive]
print(f"{Positives1}\n")
# 2nd way :
Positives2 = Arr[ Arr > 0 ]
print(f"{Positives2}\n")

# Counting Negative Numbers
NegCount1 = np.sum(Arr < 0)
# 2nd way ( incompleted ):
IsNegative = Arr < 0

# Change < -0.5 Numbers with 0
Arr[Arr < -0.5] = 0
print(f"{Arr}")

[-0.68879848 -0.90110927  0.64457158  0.64534252  0.47804901 -1.48692292
 -0.27957214  0.40904724  0.37586497  0.04884979 -1.04910449 -0.76019468
 -0.52679563  1.16638892 -0.17800351  0.01261292  0.39282656 -1.19493037
 -0.87509686  0.77391412]

[0.64457158 0.64534252 0.47804901 0.40904724 0.37586497 0.04884979
 1.16638892 0.01261292 0.39282656 0.77391412]

[0.64457158 0.64534252 0.47804901 0.40904724 0.37586497 0.04884979
 1.16638892 0.01261292 0.39282656 0.77391412]

[ 0.          0.          0.64457158  0.64534252  0.47804901  0.
 -0.27957214  0.40904724  0.37586497  0.04884979  0.          0.
  0.          1.16638892 -0.17800351  0.01261292  0.39282656  0.
  0.          0.77391412]


shift + tab

for command help

In [ ]:
import numpy as np

3+2.5*np.random.randn(2,4)

array([[ 4.33942844,  3.49608768,  0.6965683 , -0.26492443],
       [ 1.65899371,  2.99020643,  2.43679891,  0.36871895]])

### Example 4

In [14]:
import numpy as np

Matrix = np.random.randint(1,21,size=(4,4))
print(f"{Matrix}\n")

# Avg of each Col
ColMeans = np.mean(Matrix, axis=0)
print(f"{ColMeans}\n")

# Sum of each Row
RowSum = np.sum(Matrix,axis=1)
print(f"{RowSum}\n")

# Min of each Col
ColMin = np.min(Matrix,axis=0)
print(f"{ColMin}\n")

# Max of Matrix
MaxIndex = np.max(Matrix)
print(f"{MaxIndex}\n")

# Normalize Matrix ( change all element to value of [0,1])
# we had MaxIndex
MinIndex = np.min(Matrix)
NormalMatrix = (Matrix - MinIndex) / (MaxIndex - MinIndex)
print(f"{NormalMatrix}")

[[ 5  5 14  5]
 [ 5 16 18  5]
 [10 18  4 20]
 [ 6 17 15 15]]

[ 6.5  14.   12.75 11.25]

[29 44 52 53]

[5 5 4 5]

20

[[0.0625 0.0625 0.625  0.0625]
 [0.0625 0.75   0.875  0.0625]
 [0.375  0.875  0.     1.    ]
 [0.125  0.8125 0.6875 0.6875]]


### Attributes

In [15]:
import numpy as np

# 0d
Arr0 = np.array(-2.5)

# 1d
Arr1 = np.array([-14, 22, 3, 4])

# 2d
Arr2 = np.array([[1,2],
                 [3,4]])

# 3d
Arr3 = np.array([[[1,2],
                  [3,4]],
                  [[5,6],
                   [7,8]]])

# s and e
s = np.array([[1],[2],[3]])

e = np.array([[-1],
              [ 2],
              [ 4]])

# .ndim , .shape , .size
print("\n===== ndim shape size =====")
print(Arr0.ndim , Arr1.ndim , Arr2.ndim , Arr3.ndim , s.ndim , e.ndim)
print(Arr0.size , Arr1.size , Arr2.size , Arr3.size , s.size , e.size)
print(Arr0.shape , Arr1.shape , Arr2.shape , Arr3.shape , s.shape , e.shape)

# .dtype
print("\n===== dtype =====")
print(Arr0.dtype , Arr1.dtype , Arr2.dtype , Arr3.dtype , s.dtype , e.dtype)

# Methods
print("\n===== Methods =====")
print(Arr2.min()) # 1st way
print(np.min(Arr2)) # 2nd way




===== ndim shape size =====
0 1 2 3 2 2
1 4 4 8 3 3
() (4,) (2, 2) (2, 2, 2) (3, 1) (3, 1)

===== dtype =====
float64 int64 int64 int64 int64 int64

===== Methods =====
1
1


### Data type & Conversion

In [ ]:
import numpy as np

# Data Type
Arr11 = np.array([1 ,2,3,4])
Arr22 = np.array([1.,2,3,4])

print(Arr11.dtype, Arr22.dtype)
print(Arr11,Arr22)

# Define array with target data type
print("\n===== Define data type =====")
Arr1 = np.array([130,128,127,400] , dtype = np.int16)
Arr2 = np.array([1,2,255,20] , dtype = np.uint8)
print(Arr1 , Arr1.dtype , Arr2 , Arr2.dtype)

Arr3 = np.array([0,255,256,-1,-2] , dtype = np.int32)
print(Arr3 , Arr3.dtype)

Arr4 = np.array([complex(1,1),128,127,400] , dtype = np.complex64)
print(Arr4 , Arr4.dtype)

Arr5 = np.array([130,0,127,400] , np.bool_)
print(Arr5 , Arr5.dtype)

# Convert
print("\n===== Convert =====")
Arr6 = np.array([130,128,127,400] , dtype = np.int32)
print(Arr6 , Arr6.dtype)
Arr6 = Arr6.astype(np.float64)
print(Arr6.dtype)

int64 float64
[1 2 3 4] [1. 2. 3. 4.]

===== Define data type =====
[130 128 127 400] int16 [  1   2 255  20] uint8
[  0 255 256  -1  -2] int32
[  1.+1.j 128.+0.j 127.+0.j 400.+0.j] complex64
[ True False  True  True] bool

===== Convert =====
[130 128 127 400] int32
float64


### Special Arrays

In [17]:
import numpy as np

# np.zeros()
print("\n===== Zero =====")
ArrZero2d = np.zeros((3,4) , dtype = np.int16)
print(ArrZero2d)
ArrZero3d = np.zeros((5,6,4) , dtype = np.int16)
print(ArrZero3d)

# np.ones()
print("\n===== One =====")
ArrOne1d = np.ones(6)
ArrOne2d = np.ones((4,5) , dtype = np.float32)
print(ArrOne1d , ArrOne2d , ArrOne2d.dtype)

# np.eye()
print("\n===== I =====")
ArrI2d = np.eye(3,2)
ArrI1d = np.eye(3 , dtype = np.int8)
print(f"{ArrI2d}\n\n{ArrI1d}")

# np.empty()
print("\n===== Empty =====")
print(np.empty(5))

# np.full()
print("\n===== Full =====")
ArrFull1 = np.full((3,2,2) , 1.2)
ArrFull2 = np.ones((3,2,2)) * 1.2
print(f"{ArrFull1}\n\n{ArrFull2}")

print("\n===== Arange =====")
PyAr = np.array(range(2,10,2))
NpAr = np.arange(2,10,2)
print(PyAr , NpAr)

print("\n===== Linspace =====")
LinArr = np.linspace(0,9,10)
LinArr50 = np.linspace(0,9,50)
ArArr = np.arange(0,10,1)
print(LinArr , LinArr50 , ArArr)

print("\n===== Step =====")
S1 = np.linspace(0,1,100)
S2 = np.linspace(0,1)
print(f"{S1}\n{S2}")


===== Zero =====
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]

===== One =====
[1. 1. 1. 1. 1. 1.] [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] float32

===== I =====
[[1. 0.]
 [0. 1.]
 [0. 0.]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]

===== Empty =====
[0.00000000e+000 1.08174358e-311 1.08174358e-311 1.08174358e-311
 3.88554815e-317]

===== Full =====
[[[1.2 1.2]
  [1.2 1.2]]

 [[1.2 1.2]
  [1.2 1.2]]

 [[1.2 1.2]
  [1.2 1.2]]]

[[[1.2 1.2]
  [1.2 1.2]]

 [[1.2 1.2]
  [1.2 1.2]]

 [[1.2 1.2]
  [1.2 1.2]]]

===== Arange =====
[2 4 6 8] [2 4 6 8]

===== Linspace =====
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] [0.         0.183

### Create a Zero Vector with the same size as A

In [ ]:
import numpy as np

A = np.zeros((5,6,4) , dtype = np.int16)
print(A.shape , A.dtype)

# Hard way
print("\n===== Hard =====")
B1 = np.zeros(A.shape , dtype = A.dtype)
print(B1.shape , B1.dtype)

# Easy way
print("\n===== Easy =====")
B2 = np.zeros_like(A)
print(B2.shape , B2.dtype)
print("\n===== Ones =====")
B3 = np.ones_like(A)
print(B3.shape , B3.dtype)

(5, 6, 4) int16

===== Hard =====
(5, 6, 4) int16

===== Easy =====
(5, 6, 4) int16

===== Ones =====
(5, 6, 4) int16


### Random Arrays

In [19]:
import numpy as np
# or [from numpy import random]

print(np.random.rand(2))

# rand() ~U[0,1)
print("\n===== Rand ~ U[0,1) =====")
print(np.random.rand())
print(np.random.rand(2,3))
print(10 * np.random.rand() - 5)

[0.95557133 0.24771424]

===== Rand ~ U[0,1) =====
0.11791783029487168
[[0.64792616 0.74483079 0.32222082]
 [0.71414469 0.49696316 0.23618497]]
2.9879251595491247
