# HOMEWORK 5

In [252]:
# name     : Arshya Esfandiari
# uni ID   : 40334201
# homework : 5
# problem  : write all of my examples and lessons
#            from session 1405/02/21.
# ------------------------------------------------------------------------------

## LIBRARIES

In [253]:
# Required libraries
import numpy as np
import time

## VECTORIZATION

In [254]:
# The BIG ARRAY
ArrBIG = np.random.rand(10000000)

# with Loop
print("LOOP :")
Start = time.time()
MaxVal = ArrBIG[0]
for x in ArrBIG:
    if x > MaxVal:
        MaxVal = x
print(f"Time : {time.time() - Start}\nMax Value = {MaxVal}")

print("=========================")

# with Vectorization
print("VECTORIZATION :")
Start = time.time()
MaxVal = np.max(ArrBIG)
print(f"Time : {time.time() - Start}\nMax Value = {MaxVal}")

LOOP :
Time : 1.4814932346343994
Max Value = 0.9999997926060963
VECTORIZATION :
Time : 0.005266904830932617
Max Value = 0.9999997926060963


In [255]:
# Method 1
LongArr = np.arange(1,100001)
print(f"The Array :\n{LongArr}")
StartOne = time.time()
for i , v in enumerate(LongArr) :
    LongArr[i] **= 2

DeltaTimeOne = time.time() - StartOne
print(f"The Powered Array by loop :\n{LongArr}\n\nTime : {DeltaTimeOne}\nShape = {LongArr.shape}")
print("=========================")

# Method 2
LongArr = np.arange(1, 100001)
StartTwo = time.time()
LongArr **= 2
DeltaTimeTwo = time.time() - StartTwo
print(f"The Powered Array by vectorization :\n{LongArr}\n\nTime : {DeltaTimeTwo}\nShape = {LongArr.shape}")
print(f"\nTime optimization : {DeltaTimeOne / DeltaTimeTwo}")

The Array :
[     1      2      3 ...  99998  99999 100000]
The Powered Array by loop :
[          1           4           9 ...  9999600004  9999800001
 10000000000]

Time : 0.044626712799072266
Shape = (100000,)
The Powered Array by vectorization :
[          1           4           9 ...  9999600004  9999800001
 10000000000]

Time : 0.00012946128845214844
Shape = (100000,)

Time optimization : 344.7108655616943


# MATH OPERATIONS

In [256]:
A = np.random.randint(0, 10, (2, 2))
B = np.random.randint(0, 10, (2, 2))
A , B

(array([[5, 5],
        [9, 2]], dtype=int32),
 array([[4, 9],
        [4, 6]], dtype=int32))

## ADDITION AND SUBTRACTION

In [257]:
print(A + B)
print("=========================")
print(A - B)

[[ 9 14]
 [13  8]]
[[ 1 -4]
 [ 5 -4]]


In [258]:
APRIME = np.arange(1,6)
BPRIME = np.arange(5)
APRIME + BPRIME

array([1, 3, 5, 7, 9])

## MULTIPLICATION AND DIVISION

In [259]:
print(A * B) # A[i,j] x B[i,j]
A / B

[[20 45]
 [36 12]]


array([[1.25      , 0.55555556],
       [2.25      , 0.33333333]])

## MATRIX MULTIPLICATION

In [260]:
ArrOne = np.array([[1, 2, 2], [3, 4, 4]])
ArrTwo = np.array([[5, 6], [7,8], [1, 2]])

print(f"{ArrOne @ ArrTwo}\n=================")
Result = np.matmul(ArrOne, ArrTwo)
print(f'Matrix Product of ArrOne x ArrTwo :\n{Result}')

[[21 26]
 [47 58]]
Matrix Product of ArrOne x ArrTwo :
[[21 26]
 [47 58]]


In [261]:
ArrOne = np.arange(10)
print(ArrOne, ArrOne.shape)

# create Column model
ArrOneZero = ArrOne[None,:]

# np.newaxis instead of "None"
ArrOneOne = ArrOne[: , np.newaxis]

print(ArrOneZero , ArrOneOne , ArrOneZero.shape)
ArrTwo = np.arange(10)
ArrTwo = ArrTwo[:,None]
print(ArrOne.shape, ArrTwo.shape)
print("================================")
ArrOneZero @ ArrTwo
ArrTwo @ ArrOneZero

[0 1 2 3 4 5 6 7 8 9] (10,)
[[0 1 2 3 4 5 6 7 8 9]] [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] (1, 10)
(10,) (10, 1)


array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [262]:
ArrOne = np.arange(2)
ArrOne = ArrOne[None, :]
ArrTwo = np.random.randn(2, 3)

print(ArrOne.shape, ArrTwo.shape)
ArrOne @ ArrTwo

(1, 2) (2, 3)


array([[0.44258129, 0.27833825, 0.76017447]])

## BROADCASTING

In [263]:
np.ones((1,8)) + 10
print(np.ones((1,8))+10 , np.ones((1,8)).shape)

[[11. 11. 11. 11. 11. 11. 11. 11.]] (1, 8)


## SUM A VECTOR WITH A SCALAR

### [0, 1, 2] + [5] Is similar to [0, 1, 2] + [5, 5, 5] = [5, 6, 7]

In [264]:
np.arange(0, 3) + 5

array([5, 6, 7])

## SUM A MATRIX WITH A VECTOR

[[1, 1, 1]                                  [[1, 1, 1]     [[0, 1, 2]
 [1, 1, 1]   +  [0, 1, 2]  Is similar to   [1, 1, 1]  +   [0, 1, 2]
 [1, 1, 1]]                                  [1, 1, 1]]     [0, 1, 2]]

In [265]:
print(np.ones((3,3)) + np.arange(0,3))
print(np.ones((3,3)) + np.arange(0,3)[:,None])
print(np.ones((3,3)) + np.arange(0,3)[:,None])

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


## SUM A ROW VECTOR WITH A COLUMN VECTOR

In [266]:
SS1 = np.arange(0, 4)[:,None]
SS2 = np.arange(0,3)
print(f"{SS1}\n{SS2}")
print(SS1 + SS2)

[[0]
 [1]
 [2]
 [3]]
[0 1 2]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


# RULES OF BROADCASTING

1. DIMENSIONS ARE COMPARED FROM RIGHT TO LEFT
2. IF DIMENSIONS ARE EQUAL , IT'S FINE
3. IF ONE OF THE DIMENSIONS IS 1 , IT'S ALSO FINE [ THAT DIMENSION CAN BE STRETCHED TO MATCH THE OTHER ]

### (5,4,3,1) & (3,1,1)

In [267]:
np.ones((5,4,3,1)) + np.ones((3,1,1))
# IT WON'T SUM BECAUSE OF DIMENSION ERROR [ INCOMPATIBILITY OF DIMS ]

ValueError: operands could not be broadcast together with shapes (5,4,3,1) (3,1,1) 

### (4,3,1) & (2,1)

In [ ]:
print(np.ones((4,1,2)) , np.ones((2,1)))
np.ones((4,1,2)) + np.ones((2,1))

### (5,1,2,3) & (4,2,1)

In [ ]:
A = np.ones((5,1,2,3)) + np.ones((4,2,1))
A.shape

(5, 4, 2, 3)

# COMPARISON OPERATORS

## STRING INDEXING

In [ ]:
x = np.array([1, 2, 3, 1, 5])

In [ ]:
print(x == 1)
print(x > 2)
print(x >= 2)
print(x != 1)

[ True False False  True False]
[False False  True False  True]
[False  True  True False  True]
[False  True  True False  True]


In [ ]:
mask = x == 1
print(x[mask])
print(x[[True,False,False,True,False]])
print(x[x == 1])

[1 1]
[1 1]
[1 1]


In [ ]:
np.array([1,2,3,5]) == np.array([1,-1,3,1])

array([ True, False,  True, False])

In [ ]:
x**2 == 2**x

array([False,  True, False, False, False])

In [ ]:
np.arange(0,3) [:,None] == np.arange(0,3)
print(f"{np.arange(0,3) [:,None]}\n==========\n{np.arange(0,3)}\n==========\n{np.arange(0,3) [:,None] == np.arange(0,3)}")

[[0]
 [1]
 [2]]
[0 1 2]
[[ True False False]
 [False  True False]
 [False False  True]]


## BOOLEAN INDEXING

In [ ]:
print(x)
print(x[x <= 3])
print(x[x % 2 != 0])
print(x[(x <= 3)& (x % 2 != 0)])

[1 2 3 1 5]
[1 2 3 1]
[1 3 1 5]
[1 3 1]


## BOOLEAN OPERATORS

In [ ]:
x = np.random.randint(10, size=(3, 4))
print(x)

[[6 4 3 9]
 [5 4 0 7]
 [4 7 8 6]]


In [ ]:
print((x > 5) ^ (x % 2 == 0), end='\n\n')
# ^ === or

print(x % 2 == 0, end='\n\n')
print(~(x % 2 == 0), end='\n\n')
# ~ === not

print((x == 0) | (x < 6))
# | === or

[[False  True False  True]
 [False  True  True  True]
 [ True  True False False]]

[[ True  True False False]
 [False  True  True False]
 [ True False  True  True]]

[[False False  True  True]
 [ True False False  True]
 [False  True False False]]

[[False  True  True False]
 [ True  True  True False]
 [ True False False False]]


## MASK

In [ ]:
Mask = (x > 5) & (x % 2 == 0)
print(x[Mask])

[6 8 6]


In [ ]:
x[(x == 0) | (x > 8)]

array([9, 0], dtype=int32)

# TRANSFORMATION

In [ ]:
A = np.random.randint(10, size=(2, 6))
B = np.random.randn(3)
print(A)
print(B)

[[1 5 0 3 1 8]
 [5 8 4 6 8 1]]
[ 0.57209787 -0.59865127  2.61028033]


## np.transpose()

In [ ]:
np.transpose(A)
A.transpose()

array([[1, 5],
       [5, 8],
       [0, 4],
       [3, 6],
       [1, 8],
       [8, 1]], dtype=int32)

In [ ]:
print(x)
y = x.reshape(2,-1) # when we use <<-1>> when we don't know the Row or Col Num
print(y)

[[6 4 3 9]
 [5 4 0 7]
 [4 7 8 6]]
[[6 4 3 9 5 4]
 [0 7 4 7 8 6]]


In [ ]:
B = np.random.randn(1, 3)
B.transpose()

array([[-0.80362719],
       [ 1.14256146],
       [-0.63792295]])

## np.reshape()

In [ ]:
C = A.reshape(3, -1)
C

array([[1, 5, 0, 3],
       [1, 8, 5, 8],
       [4, 6, 8, 1]], dtype=int32)

In [ ]:
A.reshape(-1, 4)

array([[1, 5, 0, 3],
       [1, 8, 5, 8],
       [4, 6, 8, 1]], dtype=int32)

# CONVERT TO A VECTOR

In [ ]:
A.reshape(-1)
A.ravel()
A.shape

(2, 6)

## np.stack()

In [ ]:
np.stack((A, A, A, A)).shape

(4, 2, 6)

In [ ]:
np.stack((A, A, A, A), axis=-1).shape

(2, 6, 4)

In [ ]:
np.hstack((A, A, A, A)).shape

(2, 24)

In [ ]:
np.vstack((A, A, A, A)).shape

(8, 6)

In [ ]:
A = np.random.randint(10, size=(2,6))
B = np.random.randn(1,6)
C = np.random.randint(10, size=(2, 5))

np.hstack((A, C)).shape
np.vstack((A, B)).shape

(3, 6)

## np.split()

In [ ]:
A = np.random.randint(10, size=(2, 6))
B = np.random.randn(6)

print(B)
C, D = np.split(B, 2)
C, D

[ 0.10800946 -0.01165987  0.96518287 -0.57045164 -1.17662419 -1.26530635]


(array([ 0.10800946, -0.01165987,  0.96518287]),
 array([-0.57045164, -1.17662419, -1.26530635]))

In [ ]:
np.split(A, 2, axis=1)

[array([[1, 9, 9],
        [6, 9, 0]], dtype=int32),
 array([[1, 0, 5],
        [4, 6, 8]], dtype=int32)]

## np.repeat()

In [ ]:
A = np.random.randint(10, size=(2, 6))
B = np.random.randn(3)

print(B)
B.repeat(3)

[-0.93510729 -1.00597627  0.65637548]


array([-0.93510729, -0.93510729, -0.93510729, -1.00597627, -1.00597627,
       -1.00597627,  0.65637548,  0.65637548,  0.65637548])

In [ ]:
print(A)
A.repeat(3, axis=1)

[[0 9 4 3 9 0]
 [0 2 3 8 8 4]]


array([[0, 0, 0, 9, 9, 9, 4, 4, 4, 3, 3, 3, 9, 9, 9, 0, 0, 0],
       [0, 0, 0, 2, 2, 2, 3, 3, 3, 8, 8, 8, 8, 8, 8, 4, 4, 4]],
      dtype=int32)

# FUNCTION

## DEFINE A FUNCTION

### def <[(NameOfFunction)]> (A) : -> coding -> return <[(FunctionOutput)]> 

In [ ]:
def FOne(x) :
    y = x * 100
    return y

In [ ]:
Output = FOne(-0.5)
print(Output)

-50.0


In [ ]:
def FTwo(x1,x2) :
    y = x1**2 + x2**2
    print(y)

In [ ]:
FTwo(0.25,2)

4.0625


In [ ]:
def FThree() :
    y = 0.1**2
    print(y)
    return y

C = FThree()
print('C:',C)


0.010000000000000002
C: 0.010000000000000002


In [ ]:
# Args FOR NUMEROUS VARIABLES WITHOUT NAME
def SumOne( *Nums ) : # * MAKES THE FUNCTION INPUT CAPACITY UNLIMIT
    result = 0
    for num in Nums :
        result += num
        return result
        # YOU CAN GIVE 1 , 2 , 3 OR EVEN 100 NUMS

print(SumOne(2,4,5))
# print(SumOne(30,20,10))
# print(SumOne(5,4,3,2,1))

2


In [ ]:
def FFour(x, y) :
    S = x**2 + y**2
    T = x**2 - y**2
    return S,T,x,y

In [ ]:
# IF WE WANT TO CONTAIN OUTPUTS OF FUNCTION IN SEPARATE VARIABLES
OutOne , OutTwo , OutThree , OutFour = FFour(132.351, 567.13)
print(OutOne , OutTwo , OutThree , OutFour)

339153.224101 -304119.64969899994 132.351 567.13


In [ ]:
# WE SEPARATE ONE VARIABLE FROM OTHERS
OutFive , *OutSix = FFour(132.351, 567.13)
print(OutFive , *OutSix)

339153.224101 -304119.64969899994 132.351 567.13


In [ ]:
Out = FFour(132.351, 567.13)
print(Out)

(339153.224101, -304119.64969899994, 132.351, 567.13)


In [250]:
OutZ1, *OutZ2 = FFour(0.1, 0.1)
print(OutZ1)
print(OutZ2)

0.020000000000000004
[0.0, 0.1, 0.1]


# CALCULATOR

In [251]:
def Calculator(): # A SIMPLE CALCULATOR WITH VARIOUS FEATURES
    def Plus(a , b) :
        return a + b
    
    def Minus(a, b) :
        return a - b
    
    def Times(a, b) :
        return a * b
    
    def Divide(a , b) :
        if b == 0 :
            return "ERROR ! DENOMINATOR IS 0 !!!"
        return a / b

    print("====== Calculator ======")
    print("Operations :\nSummation+ ( P )\nSubtraction- ( M )\nMultiplicationx ( T )\nDivision÷ ( D )")
    while True :
        Operation = input("PLEASE CHOSE THE OPERATOR [ EXIT = 'E' ] : >")
        if Operation == 'E' :
            break
        
        if Operation in ['P','M','T','D'] :
            a = float(input("FIRST NUM  : >"))
            b = float(input("SECOND NUM : >:"))
            if Operation == 'P' :
                print(f"RESULT = {Plus(a, b)}\n==========")
            elif Operation == 'M' :
                print(f"RESULT = {Minus(a, b)}\n==========")
            elif Operation == 'T' :
                print(f"RESULT = {Times(a, b)}\n==========")
            elif Operation == 'D' :
                print(f"RESULT = {Divide(a, b)}\n==========")
        else:
            print("INVALID INPUT!\nHINT : PLEASE ENTER THE OPERATOR LETTER CAPITALCASE")

# Run Calc
Calculator()

====== Calculator ======
Operations :
Summation+ ( P )
Subtraction- ( M )
Multiplicationx ( T )
Division÷ ( D )
