# HOMEWORK 7

In [ ]:
# name     : Arshya Esfandiari
# uni ID   : 40334201
# homework : 7
# problem  : write all of my examples and lessons
#            from session 1405/03/04.
# ------------------------------------------------------------------------------

In [ ]:
# Import libraries
import numpy as np
import sympy as sp
import SurveyingLib as srv
import matplotlib.pyplot as plt

In [3]:
DMSC = np.array([[2,3,4]])
print(DMSC)
print("====================")
print(srv.DMS2Decimal(DMSC))

[[2 3 4]]
[[2.05111111]]


### System of Equations
$$L = AX -> L_{m\times 1} = A_{m\times n} X_{n\times 1}$$
For systems with the condition $n < m$ :
$$Rank_{max}[A] = n < m$$
$$df = m - n$$
Least square method : finds the best estimate by minimizing the norm of the residual error vector.
$$\hat x = (A^T A)^{-1} A^T L$$
Weight matrix : $W_{m\times m}$
$$\hat x = (A^T WA)^{-1} A^T WL$$
The Best Linear Unbiased Estimator (BLUE) :
$$W = Q_L^{-1} -> \hat x = (A^T Q_L^{-1}A)^-1 A^T Q_L^{-1}L

### EXAMPLE 1 : Create the W and Cov matrices

In [4]:
def CovWeightMatrix(Vars) :
    Cov = np.diag(Vars)
    Weight = np.linalg.inv(Cov)
    return Cov , Weight

# Variance of Observations
Variances = np.array([2,3,4]) # SIGMA^2 -> mm^2

# Diagonal Cov matrix & Weight matrix [ the inverse of Diagonal Cov ]
Cov , Weight = CovWeightMatrix(Variances)
print(f"Cov matrix :\n{Cov}")
print(f"Weight matrix :\n{Weight}")

Cov matrix :
[[2 0 0]
 [0 3 0]
 [0 0 4]]
Weight matrix :
[[0.5        0.         0.        ]
 [0.         0.33333333 0.        ]
 [0.         0.         0.25      ]]


### EXAMPLE 2 : Solve the System of Equations
the L = AX -> np.linalg.solve()

In [5]:
# +6x - 2y = +10
# -2x + 4y = -4
# ===================================
# Defining the A and L and solve X
A = np.array([[6,-2],
              [-2,4]])
L = np.array([[10],
              [-4]])
X = np.linalg.solve(A,L)
print(f"The Unknowns [numpy] :\n{X}")

# Using xHat formula
ATA = A.T @ A
ATL = A.T @ L
X = np.linalg.inv(ATA) @ ATL

# Display the result
print(f"X =\n{X}")

The Unknowns [numpy] :
[[ 1.6]
 [-0.2]]
X =
[[ 1.6]
 [-0.2]]


### EXAMPLE 3 : Solve with Least Square

In [9]:
# Defining the A and L and solve X
A = np.array([[1, 0],
              [1, 1],
              [0, 1]])
L = np.array([[100.2],
              [101.4],
              [99.8]])

# Using xHat formula
ATA = A.T @ A
ATL = A.T @ L
X = np.linalg.inv(ATA) @ ATL

# Residual vector
V = A @ X - L

# Display the result
print(f"ATA :\n{ATA}\n")
print(f"ATL :\n{ATL}\n")
print(f"X Unknowns :\n{X}\n")
print(f"V Residuals :\n{V}\n")

ATA :
[[2 1]
 [1 2]]

ATL :
[[201.6]
 [201.2]]

X Unknowns :
[[67.33333333]
 [66.93333333]]

V Residuals :
[[-32.86666667]
 [ 32.86666667]
 [-32.86666667]]



## PARAMETRIC MODEL
if we want to write the Observations based on the Unknowns , this model is called "Parametric model" :
<br><br>
$$L = F(x) \xrightarrow{\text{ Derivate }} Coefficients$$
<br><br>
$$Coefficients \xrightarrow{\text{    Matrix    }} A$$
<br><br>
$$\hat x = (A^T PA)^{-1} A^T PL$$
<br><br>
$$\sigma _{\hat x\hat x} = \sigma _0 ^2 (A^T PA)^{-1}$$
<br><br>
$$\hat v = A\hat x - L$$
<br><br>
$$\sigma _{\hat v\hat v} = \sigma _0 ^2 (P^{-1} - A(A^T PA)^{-1} A^T)$$
<br><br>
$$\hat L = L + \hat v$$
<br><br>
$$\sigma _{\hat L\hat L} = \sigma _0 ^2 A(A^T PA)^{-1} A^T$$

### EXAMPLE 4 : Estimate the accuracy of Unknowns

In [6]:
A = np.array([[1,0],[1,1],[0,1]])
SigmaZeroSQ = 1 # A Posteriori Variance of Unit Weight

ATA = A.T @ A
CovXX = SigmaZeroSQ * np.linalg.inv(ATA)

STDX = np.sqrt(np.diag(CovXX))

print(f"Covariance matrix of Unknowns :\n{CovXX}")
print(f"Standard Deviation of Unknowns :\n{STDX}")

Covariance matrix of Unknowns :
[[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]
Standard Deviation of Unknowns :
[0.81649658 0.81649658]


## MATRIX AND VECTOR OPERATIONS

In [7]:
# ==================================================
#      FUNDAMENTAL MATRIX AND VECTOR OPERATIONS
# ==================================================

# Define the vectors
V1 = np.random.randint(-10, 11, size=(3,))
V2 = np.random.randint(-10, 11, size=(3,))
V3 = np.random.randint(-10, 11, size=(3,))
print(f"The vectors :\nV1 =\n{V1}\nV2 =\n{V2}\nV3 =\n{V3}")
print("====================")

# 3x3 Matrix
M1 = np.random.randint(2, 11, size=(3, 3))
M2 = np.random.randint(2, 11, size=(3, 3))
M3 = np.random.randint(2, 11, size=(2, 4))
print(f"The matrices :\nM1 = {M1}\n M2 = {M2}\nM3 = {M3}")
print("====================")

# Vector Operations
print("VECTOR OPERATIONS\n")
print(f"Vector Summation      = V1 + V2 =\n{V1 + V2}")
print(f"Vector Subtraction    = V1 - V2 =\n{V1 - V2}")
print(f"Dot Product           = V1 . V2 =\n{np.dot(V1,V2)}")
print(f"Cross Product         = V1 x V2 =\n{np.cross(V1,V2)}")
print(f"Norm of a vector      = ||V1||  =\n{np.linalg.norm(V1)}")
print(f"Normalize the vector  = N(V1)   =\n{V1 / np.linalg.norm(V1)}")

# Matrix Operations
print("MATRIX OPERATIONS\n")
print(f"Matrix Summation  = M1 + M2 =\n{M1 + M2}")
print(f"Matrix Multiplication :\nnp.dot(M1,M2) =\n{np.dot(M1,M2)}\nM1 * M2 =\n{M1 * M2}")
print(f"Hadamard Product  = M1 @ M2 =\n{M1 @ M2}")
print(f"Matrix Transpose  = M1.T    =\n{M1.T}")
print(f"Trace of Matrix   = np.trace(M1) =\n{np.trace(M1)}")
print(f"Determinant       = np.linalg.det(M1) =\n{np.linalg.det(M1)}")

# Advanced Operations
EigVal , EigVec = np.linalg.eig(M1) # EigenValues and EigenVectors
U , S , VTrn = np.linalg.svd(M1) # Singular Value Decomposition
InvA = np.linalg.inv(M1) # Inverse of a matrix
PInvA = np.linalg.pinv(M3)
print("ADVANCED OPERATIONS")
print(f"Eigen Values of M1    =\n{EigVal}")
print(f"Eigen Vector of M1    =\n{EigVec}")
print(f"Singular Values of M1 =\n{S}")
print(f"Inverse of M1         =\n{InvA}")
print(f"Psuedo Inverse of M3  =\n[non-square] 4x2 :\n{PInvA}")

The vectors :
V1 =
[-2 -5 10]
V2 =
[-7  4 -5]
V3 =
[-8 10  7]
The matrices :
M1 = [[ 8  4  5]
 [ 9  6  5]
 [10  4  6]]
 M2 = [[4 2 7]
 [8 6 6]
 [6 8 8]]
M3 = [[ 8  6  7  7]
 [ 9 10  7  8]]
VECTOR OPERATIONS

Vector Summation      = V1 + V2 =
[-9 -1  5]
Vector Subtraction    = V1 - V2 =
[ 5 -9 15]
Dot Product           = V1 . V2 =
-56
Cross Product         = V1 x V2 =
[-15 -80 -43]
Norm of a vector      = ||V1||  =
11.357816691600547
Normalize the vector  = N(V1)   =
[-0.17609018 -0.44022545  0.88045091]
MATRIX OPERATIONS

Matrix Summation  = M1 + M2 =
[[12  6 12]
 [17 12 11]
 [16 12 14]]
Matrix Multiplication :
np.dot(M1,M2) =
[[ 94  80 120]
 [114  94 139]
 [108  92 142]]
M1 * M2 =
[[32  8 35]
 [72 36 30]
 [60 32 48]]
Hadamard Product  = M1 @ M2 =
[[ 94  80 120]
 [114  94 139]
 [108  92 142]]
Matrix Transpose  = M1.T    =
[[ 8  9 10]
 [ 4  6  4]
 [ 5  5  6]]
Trace of Matrix   = np.trace(M1) =
20
Determinant       = np.linalg.det(M1) =
-7.999999999999995
ADVANCED OPERATIONS
Eigen Values

<>:11: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:11: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\Linux\AppData\Local\Temp\ipykernel_16688\3061958227.py:11: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [-1,1]


TypeError: list indices must be integers or slices, not tuple

### EXAMPLE 5 : We want to calculate the Height of all points in a Leveling network with 1 known point [ = 100m ]

$$H_1 = 100m$$
$$\Delta H_{12} = 5.430m$$
$$\Delta H_{23} = 2.380m$$
$$\Delta H_{31} = 7.790m$$
<p align="center">
  <img src="hw7-p1.png" width="500"/>
</p>

In [ ]:
H1 = 100
DH12 = 5.430
DH23 = 2.380
DH31 = 7.790

# DH12 + H1 = H2
# DH23 = H3 - H2
# DH31 - H1 = H3

A = np.array([[1,0],
              [-1,1]
              [0,-1]])

L = np.array([DH12 + H1 , DH23 , DH31 - H1])
LColumn = L.reshape(-1,1)

ATA = A.T @ A
ATL = A.T @ L
XHat1 = np.linalg.inv(ATA) @ ATL

print(f"L :\n{LColumn}\nXHat :{XHat1}\n")
XHat2 = np.linalg.lstsq(A,L,rcond = 0)
print(f"XHat 2 :\n{XHat2}")

In [ ]:
H1 = 100
DH12 = 5.430
DH23 = 2.380
DH31 = 7.790

# DH12 + H1 = H2
# DH23 = H3 - H2
# DH31 - H1 = H3

A = np.array([[+1,+0],
              [-1,+1],
              [+0,-1]])

L = np.array([DH12 + H1 , DH23 , DH31 - H1])
LCol = L.reshape(-1,1)

ATA = A.T @ A
ATL = A.T @ LCol
XHat1 = np.linalg.inv(ATA) @ ATL
XHat2 = np.linalg.lstsq(A , L , rcond = 0)

print(f"L :\n{LCol}")
print(f"XHat ( ata^-1 atl )   :\n{XHat1}")
print(f"XHat ( lstsq method ) :\n{XHat2}")

In [ ]:
H1 = 100
DH12 = 5.430
DH23 = 2.380
DH31 = 7.790

# DH12 + H1 = H2
# DH23 = H3 - H2
# DH31 - H1 = H3

L = np.array([DH12 + H1 , DH23 , DH31 - H1])

H2 , H3 = sp.symbols("H2 H3")

L1 = H2 - H1
L2 = H3 - H2
L3 = H1 - H3

X = sp.Matrix([H2 , H3])

# ASym = sp.Matrix([H2 , H3])
ASym = sp.Matrix([[sp.diff(L1,H2),sp.diff(L1,H3)],
                  [sp.diff(L2,H2),sp.diff(L2,H3)],
                  [sp.diff(L3,H2),sp.diff(L3,H3)]])

# convert to Numpy array with "float" type
A = np.array(ASym).astype(float)
LCol = L.reshape(-1,1)

ATA = A.T @ A
ATL = A.T @ L
XHat1 = np.linalg.inv(ATA) @ ATL

print(f"A :\n{A}\nL :\n{L}\nXHat with normal method :\n{XHat1.flatten()}")

XHat2 , residuals , rank , s = np.linalg.lstsq(A , L , rcond = None)
print("XHat with lstsq method :\n{XHat2}")

In [ ]:
H1 = 100
DH12 = 5.430
DH23 = 2.380
DH31 = 7.790

# DH12 + H1 = H2
# DH23 = H3 - H2
# DH31 - H1 = H3

L = np.array([DH12 + H1 , DH23 , DH31 - H1])

H2 , H3 = sp.symbols("H2 H3")

L1 = H2 - H1
L2 = H3 - H2
L3 = H1 - H3

DH = sp.Matrix([[L1],
                [L2],
                [L3]])

X = sp.Matrix([H2 , H3])

# ASym = sp.Matrix([H2 , H3])
ASym = DH.jacobian(X)

# convert to Numpy array with "float" type
A = np.array(ASym).astype(float)
LCol = L.reshape(-1,1)

ATA = A.T @ A
ATL = A.T @ L
XHat1 = np.linalg.inv(ATA) @ ATL

print(f"A :\n{A}\nL :\n{L}\nXHat with normal method :\n{XHat1.flatten()}")

# method 2 : Least Square
XHat2 , residuals , rank , s = np.linalg.lstsq(A , L , rcond = None)
print("XHat with lstsq method :\n{XHat2}")

### EXAMPLE 6 : In a Leveling network , 2 points have known heights. Calculate the height of other points
$$H_4 = 100.00m$$
$$H_5 = 100.28m$$
$$\Delta H_{41} = +1.30m$$
$$\Delta H_{15} = -1.00m$$
$$\Delta H_{53} = -0.27m$$
$$\Delta H_{31} = -1.30m$$
$$\Delta H_{52} = -0.50m$$
$$\Delta H_{23} = +0.26m$$
$$\sigma = 2mm = 0.002m$$
<p align="center">
  <img src="hw7-p2.png" width="500"/>
</p>


In [ ]:
# from scipy.linalg import inv

# initial data
H4 = 100
H5 = 100.28

DH = np.array([1.3,-1,-0.27,-1.3,-0.5,0.26]).reshape(-1,1)
DH41 = 1.3   # DH41 = H1 - H4 -> DH41 + H4 = +H1
DH15 = -1.0  # DH15 = H5 - H1 -> DH15 - H5 = -H1
DH53 = -0.27 # DH53 = H3 - H5 -> DH53 + H5 = H3
DH31 = -1.3
DH52 = -0.5
DH23 = 0.26
# Numerical L
L = np.array([DH[0] + H4 , DH[1] - H5 , DH[2] + H5 , DH[3] , DH[4] + DH[5] , DH[5]]).reshape(-1,1)

print(f"L :\n{L}")
Sigma = 0.002 # 2mm = 0.2cm = 0.002m
QL = np.pow(Sigma,2) * np.eye(6)

# Symbolic Variables
H1 , H2 , H3 = sp.symbols('H1 H2 H3')

# Define L1 to L6 symbolic
L1 = H1
L2 = -H1
L3 = H3
L4 = H1 - H3
L5 = H2
L6 = H3 - H2

# Symbolic A Matrix
ASym = sp.zeros(0,3)
ASym[0,0] = sp.diff(L1,H1)
ASym[0,1] = sp.diff(L1,H2)
ASym[0,2] = sp.diff(L1,H3)

ASym[1,0] = sp.diff(L2,H1)
ASym[1,1] = sp.diff(L2,H2)
ASym[1,2] = sp.diff(L2,H3)

ASym[2,0] = sp.diff(L3,H1)
ASym[2,1] = sp.diff(L3,H2)
ASym[2,2] = sp.diff(L3,H3)

ASym[3,0] = sp.diff(L4,H1)
ASym[3,1] = sp.diff(L4,H2)
ASym[3,2] = sp.diff(L4,H3)

ASym[4,0] = sp.diff(L5,H1)
ASym[4,1] = sp.diff(L5,H2)
ASym[4,2] = sp.diff(L5,H3)

ASym[5,0] = sp.diff(L6,H1)
ASym[5,1] = sp.diff(L6,H2)
ASym[5,2] = sp.diff(L6,H3)

# Transform Symbolic Matrix to Numerical [ because every ij is constant ]
ANum = np.array(ASym , dtype = np.float64)
print(f"ANum :\n{ANum}")

# Calculate estimated parameters with LeastSquare
W = np.linalg.inv(QL)
print(f"W :\n{W}")
ATWA = ANum.T @ W @ ANum
ATWL = ANum.T @ W @ L
XHat = np.linalg.inv(ATWA) @ ATWL
LHat = ANum @ XHat
eHat = L - LHat

# Display Result
print(f"Observations :\n{L.flatten}")
print(f"Matrix A [ Numerical ] :\n{ANum}")
print(f"Estimated Parameters [ xHat ] :\n{XHat.flatten}")
print(f"Predict the L [ lHat ] :\n{LHat.flatten}")
print(f"Residues [ eHat ] :\n{eHat.flatten}")

In [ ]:
# from scipy.linalg

# initial data
H4 = 100
H5 = 100.28

DH = np.array([1.3,-1,-0.27,-1.3,-0.5,0.26]).reshape(-1,1)
DH41 = 1.3   # DH41 = H1 - H4 -> DH41 + H4 = +H1
DH15 = -1.0  # DH15 = H5 - H1 -> DH15 - H5 = -H1
DH53 = -0.27 # DH53 = H3 - H5 -> DH53 + H5 = H3
DH31 = -1.3
DH52 = -0.5
DH23 = 0.26
# Numerical L
L = np.array([DH[0] + H4 , DH[1] - H5 , DH[2] + H5 , DH[3] , DH[4] + [5] , DH[5]]).reshape(-1,1)

print(f"L :\n{L}")
Sigma = 0.002 # 2mm = 0.2cm = 0.002m
QL = np.pow(Sigma,2) * np.eye(6)

# Symbolic Variables
H1 , H2 , H3 = sp.symbols('H1 H2 H3')

# Define L1 to L6 symbolic
L1 = H1
L2 = -H1
L3 = H3
L4 = H1 - H3
L5 = H2
L6 = H3 - H2
LSym = sp.Matrix([[L1],[L2],[L3],[L4],[L5],[L6]])
X = sp.Matrix([H1,H2,H3])

# Symbolic A Matrix
ASym = LSym.jacobian(X)

# Transform Symbolic Matrix to Numerical [ because every ij is constant ]
ANum = np.array(ASym , dtype = np.float64)
print(f"ANum :\n{ANum}")

# Calculate estimated parameters with LeastSquare
InvQL = np.linalg.inv(QL)
print(f"InvQL :\n{InvQL}")
ATWA = ANum.T @ InvQL @ ANum
ATWL = ANum.T @ InvQL @ L
XHat = np.linalg.inv(ATWA) @ ATWL
LHat = ANum @ XHat
eHat = L - LHat

# Display Result
print(f"Observations :\n{L.flatten}")
print(f"Matrix A [ Numerical ] :\n{ANum}")
print(f"Estimated Parameters [ xHat ] :\n{XHat.flatten}")
print(f"Predict the L [ lHat ] :\n{LHat.flatten}")
print(f"Residues [ eHat ] :\n{eHat.flatten}")