# FUNCTION HOMEWORK

Name : Arshya<br>
Surename : Esfandiari<br>
Uni ID : 40334201<br>
Homework : 11 Function Problems

In [30]:
import numpy as np
# this is for all codes inside this notebook

### PROBLEM 1 : Convert Polar to Decart and Vice Versa

In [31]:
import numpy as np
def P2D (UserP) :
    """
    Convert Polar to Decart coordinates.
    
    Input: 2D array [[Radius , Angle], ...] where angle in degrees or radians
    Output: (x , y)
    
    Example:
    >>> P2D(np.array([[5 , 30]]))  # Radius = 5 , Angle = 30 degrees
    (array([4.33]), array([2.5]))
    """
    # x = rCos[theta] , y = rSin[theta]
    if np.any(UserP[:,0] < 0)  :
        return "Math is not Mathing! Negative Radius? Seriously?!"
    while True :
        UserAnswer = input("What kind of angle ? a. Degree\tb. Radian\n\t>>")
        match(UserAnswer) :
            case "a" :
                x = UserP[:,0] * np.cos(np.radians(UserP[:,1]))
                y = UserP[:,0] * np.sin(np.radians(UserP[:,1]))
                return np.column_stack((np.round(x,10),np.round(y,10)))
            case "b" :
                x = UserP[:,0] * np.cos(UserP[:,1])
                y = UserP[:,0] * np.sin(UserP[:,1])
                return np.column_stack((np.round(x,10),np.round(y,10)))
            case _ :
                print("ERROR! INVALID VALUE!")

def D2P(UserP) :
    """
    Convert Decart to Polar coordinates.
    
    Input : 2D array [[x , y], ...]
    Output : (Radius , Angle)
    
    Example :
    >>> P2D(np.array([[2 , -2]]))  # x = 2 , y = -2
    (array([2 . sqrt(2)]), array([-45])) -> deg
    (array([2 . sqrt(2)]), array([sqrt(2) / 2]) -> rad
    """
    UserX = UserP[:,0]
    UserY = UserP[:,1]
    # radius = (x^2 + y^2)^0.5 , angle = ArcTan(y/x)
    while True :
        UserAnswer = input("What kind of angle ? a. Degree\tb. Radian\n\t>>")
        match(UserAnswer) :
            case "a" :
                Radius = np.sqrt(np.pow(UserX,2) + np.pow(UserY,2))
                Angle = np.degrees(np.atan2(UserY , UserX))
                return np.column_stack((Radius , Angle))
            case "b" :
                Radius = np.sqrt(np.pow(UserX,2) + np.pow(UserY,2))
                Angle = np.atan2(UserY , UserX)
                return np.column_stack((Radius , Angle))
            case _ :
                print("ERROR! INVALID VALUE!")
 

UserNum = np.array([[2,-32],[8,92],[5,-12],[7,50],[50,90]])
Converted = P2D(UserNum)
ConvertedBack = D2P(Converted)
print(f"At first , it was polar :\n{UserNum}\nThen , it converted to decart :\n{Converted}\nAnd then , it converted back to polar :\n{ConvertedBack}")

At first , it was polar :
[[  2 -32]
 [  8  92]
 [  5 -12]
 [  7  50]
 [ 50  90]]
Then , it converted to decart :
[[ 1.69609619 -1.05983853]
 [-0.27919597  7.99512662]
 [ 4.890738   -1.03955845]
 [ 4.49951327  5.3623111 ]
 [ 0.         50.        ]]
And then , it converted back to polar :
[[  2. -32.]
 [  8.  92.]
 [  5. -12.]
 [  7.  50.]
 [ 50.  90.]]


### PROBLEM 2 : Interpolate line between two points

In [32]:
import numpy as np
def IPolate (Pt1 , Pt2 , NumOfPts) :
    if type(NumOfPts) is not int :
        return "0.33 of a phone please :|"
    XLin = np.linspace(Pt1[0],Pt2[0],NumOfPts + 2)
    YLin = np.linspace(Pt1[1],Pt2[1],NumOfPts + 2)
    while True :
        UserAnswer = input("Do you want the first and the last point ?\na. yes\tb. no\t>>")
        match(UserAnswer) :
            case "a" :
                break
            case "b" :
                XLin = XLin[1:-1]
                YLin = YLin[1:-1]
                break
            case _ :
                print("ERROR! INVALID VALUE!")
                break
    LSpacePoints = np.array([XLin.T , YLin.T])
    return LSpacePoints
    
UserNum = IPolate([2,2],[-2,1],5)
print(UserNum)

[[ 2.          1.33333333  0.66666667  0.         -0.66666667 -1.33333333
  -2.        ]
 [ 2.          1.83333333  1.66666667  1.5         1.33333333  1.16666667
   1.        ]]


### PROBLEM 3 : Area of a polygon

In [33]:
import numpy as np

def ListPLArea(UserP) :
    Area = 0
    UserP.append(UserP[0])
    for i in range(len(UserP) - 1) :
        x1 , y1 = UserP[i]
        x2 , y2 = UserP[i+1]
        Area += abs((x1 * y2) - (x2 * y1))
    return 0.5 * Area

def ArrayPLArea(UserP) :
    UserP = np.append(UserP,UserP[0,:].reshape(1,-1),axis = 0)
    PtX = UserP[:,0]
    PtY = UserP[:,1]
    XinY = PtX[0:-1] * PtY[1:]
    YinX = PtY[0:-1] * PtX[1:]
    Area = np.sum(0.5 * np.abs(XinY - YinX))
    return Area

UserP1 = np.array([[-2,-2],[-2,2],[2,2],[2,-2]])
UserP2 = [[0,0],[0,4],[4,4],[4,0]]
Area1 = ArrayPLArea(UserP1)
Area2 = ListPLArea(UserP2)
print(Area1)
print(Area2)

16.0
16.0


### EXAMPLE 4 : GPS Stations Data Management by functions

In [34]:
import numpy as np

def LPXYZDist(IDs , X , Y , Z) :
    Distances = np.zeros((len(IDs) , len(IDs)))
    for i in range(len(IDs)) :
        for j in range(len(IDs)) :
            Distances[i , j] = np.sqrt((X[i] - X[j])**2 + (Y[i] - Y[j])**2 + (Z[i] - Z[j])**2)
    return Distances

def BRXYZDist(IDs , X , Y , Z , Pt = None) :
    # Reshape to column vectors
    XColumn = np.array(X).reshape(-1 , 1)
    YColumn = np.array(Y).reshape(-1, 1)
    ZColumn = np.array(Z).reshape(-1, 1)

    # Broadcasting does the rest
    Distances = np.sqrt((XColumn - X)**2 + (YColumn - Y)**2 + (ZColumn - Z)**2)
    
    if Pt is not None:
        Pt = np.array(Pt)
        Pts = np.array([X , Y , Z]).T
        Dx = Pts - Pt
        DistFromPt = np.sqrt(np.sum(Dx**2 , axis=1)) 
        return Distances , np.min(DistFromPt)
    else:
        return Distances
IDs = [1,2,3,4]
X = [0,9,4,1]
Y = [10,34,2,-4]
Z = [6,-3,100,-200]
print(LPXYZDist(IDs , X , Y , Z))
print("+================")
print(BRXYZDist(IDs , X , Y , Z))
print("+================")
print(BRXYZDist(IDs , X , Y , Z , Pt = np.array([-9,6,-3])))

[[  0.          27.16615541  94.42457307 206.47760169]
 [ 27.16615541   0.         107.97221865 200.79093605]
 [ 94.42457307 107.97221865   0.         300.07499063]
 [206.47760169 200.79093605 300.07499063   0.        ]]
+================
[[  0.          27.16615541  94.42457307 206.47760169]
 [ 27.16615541   0.         107.97221865 200.79093605]
 [ 94.42457307 107.97221865   0.         300.07499063]
 [206.47760169 200.79093605 300.07499063   0.        ]]
+================
(array([[  0.        ,  27.16615541,  94.42457307, 206.47760169],
       [ 27.16615541,   0.        , 107.97221865, 200.79093605],
       [ 94.42457307, 107.97221865,   0.        , 300.07499063],
       [206.47760169, 200.79093605, 300.07499063,   0.        ]]), np.float64(13.341664064126334))


### EXAMPLE 5 : Two Number Operations

In [35]:
import numpy as np
def SSMD(NumOne , NumTwo) :
    if NumTwo == 0 :
        return "The Denominator should not be ZERO!"
    return [NumOne + NumTwo , NumTwo - NumOne , NumOne * NumTwo , NumTwo / NumOne]

a , b = 2 , 4
print(SSMD(a,b))

[6, 2, 8, 2.0]


### EXAMPLE 6 : Prime number

In [36]:
import numpy as np
def IsPrime(num) :
    match(num) :
        case num if num < 0 :
            return "Negative ?! Really ?!"
        case num if (num == 0) | (num == 1) :
            return f"Wrong key ? or lack of knowledge ? because {num} is no either Prime or Composite !"
        case num if num == 2 :
            return "Absolutely ! It is the only Even Prime number !"
        case num if num % 2 == 0 :
            return "If you want to ensure the code works fine , it works fine !"
        case num if num >= 3 :
            for i in range(3 , int(pow(num , 13/26)) + 1, 2) :
                if num % i == 0 :
                    return "Your number IS NOT Prime !"
            return "Your number IS Prime !"
        case _ :
            return "Error ! Invalid Value"
        
def WhichIsPrime(NumOne , NumTwo) :
    UserP = range(NumOne , NumTwo + 1)
    PrimeNums = []
    for i in range(len(UserP)) :
        con = IsPrime(UserP[i])
        if con == "Your number IS Prime !" or con == "Absolutely ! It is the only Even Prime number !" :
            PrimeNums.append(UserP[i])
    return PrimeNums
            

print(IsPrime(-3))
print(IsPrime(0))
print(IsPrime(2))
print(IsPrime(3))
print(IsPrime(6))
print(IsPrime(9))
print(WhichIsPrime(5,85))

Negative ?! Really ?!
Wrong key ? or lack of knowledge ? because 0 is no either Prime or Composite !
Absolutely ! It is the only Even Prime number !
Your number IS Prime !
If you want to ensure the code works fine , it works fine !
Your number IS NOT Prime !
[5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83]


### EXAMPLE 7 : Fibonacci sequence

In [37]:
import numpy as np
def Fibonacci(NumOfItr) :
    # We used to solve it in Linear Algebra lecture
    DesignMatrix = np.array([[1, 1],[1, 0]])
    AOne = np.array([1, 0])
    return (np.linalg.matrix_power(DesignMatrix, NumOfItr) @ AOne)[1]

print(Fibonacci(20))

6765


### EXAMPLE 8 : Default and Optional Argument Management

In [ ]:
import math
import numpy as np
def CirclePA(Radius = 1) :
    Area = math.pi * pow(Radius , 2)
    Perimeter = 2 * math.pi * Radius
    
def AngleConvert(Angle , Radians = True) :
    if Radians is True :
        Radianed = np.radians(Angle)
        return Radianed
    else :
        Degreed = np.degrees(Angle)
        return Degreed

### EXAMPLE 9 : Functions with Variable number of arguments

In [39]:
def AvgAndStd(*Nums) :
    Numbers = []
    for num in Nums :
        Numbers.append(num)
    Numbers = np.array(Numbers)
    Avg = np.sum(Nums) / len(Nums)
    Std = np.std(Nums)
    return Avg , Std

print(AvgAndStd(2,3,4,5,6,7,3,2,3,1,1,6,8,3,8,8,9,6,9,5,8))

(np.float64(5.095238095238095), np.float64(2.5986216475509054))


### EXAMPLE 10 : Validate input

In [40]:
import numpy as np
def ValidateNums(UserP = np.empty(1)) :
    UserP = np.array(UserP)
    if np.all(UserP > 0) :
        return np.sum(UserP)
    elif np.any(UserP <= 0) :
        return "Warning ! There is at least one non-positive number !"
    elif np.isnan(UserP).all() :
        print("The input is empty !")
        return 0

a = ValidateNums(np.array([1,2,3,4,5,5]))
b = ValidateNums(np.array([1,-2,3,-4,5,5]))
c = ValidateNums(np.array([]))
print(a)
print(b)
print(c)

20
Warning ! There is at least one non-positive number !
0.0


### EXAMPLE 11 : A FUNC AS INPUT OF A DEF

In [41]:
import numpy as np
def FuncOnList(x, F):
    Result = []
    for i in x :
        Result.append(F(i))
    return Result

def FuncOnList2(x , F) :
    x = F(x)
    return x

Nums = [1, 2, 3, 45, 6, 7, 8, 9, 45, 3547, 1347458, 46837785368]
a = FuncOnList(x = Nums , F = np.sqrt)
for i in range(len(Nums)):
    print(f"{a[i]}", end="   ")
b = FuncOnList2(x = np.array(Nums) , F = np.sqrt)
print(f"\n{b}")

1.0   1.4142135623730951   1.7320508075688772   6.708203932499369   2.449489742783178   2.6457513110645907   2.8284271247461903   3.0   6.708203932499369   59.55669567731239   1160.8005858027468   216420.39037022367   
[1.00000000e+00 1.41421356e+00 1.73205081e+00 6.70820393e+00
 2.44948974e+00 2.64575131e+00 2.82842712e+00 3.00000000e+00
 6.70820393e+00 5.95566957e+01 1.16080059e+03 2.16420390e+05]
